version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./server  # Path to your backend directory
      dockerfile: Dockerfile
    container_name: job_recruitment_server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app  # For hot reloading (optional)
      - /app/node_modules  # Prevent overwriting node_modules
    networks:
      - job_recruitment_network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./client  # Path to your frontend directory
      dockerfile: Dockerfile
    container_name: job_recruitment_client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000  # Backend API URL
    volumes:
      - ./client:/app  # For hot reloading (optional)
      - /app/node_modules  # Prevent overwriting node_modules
    networks:
      - job_recruitment_network
    depends_on:
      - backend
    restart: unless-stopped


networks:
  job_recruitment_network:
    driver: bridge
